name: NPM CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    - run: npm install
    - run: npm install -g vsce
    - run: vsce package
    - name: get-npm-version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@master
    - uses: actions/upload-artifact@v2
      with:
        name: dark-minus-theme-${{ steps.package-version.outputs.current-version}}-nightly
        path: dark-minus-theme-${{ steps.package-version.outputs.current-version}}.vsix
