name: NPM CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest # (martinbeentjes/npm-get-version-action@master is only supported on Linux)
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: npm install
    - run: npm install -g vsce
    - run: vsce package
    # Fails with:
    # Error: Path does not exist /home/runner/work/dark-minus-theme-vscode/dark-minus-theme-vscode/dark-minus-theme-SimplifiedversionsofthedefaultDark(VisualStudio)themewithlesssyntaxhighlight.vsix
    # ???
    # - uses: martinbeentjes/npm-get-version-action@master
    #   id: package-version
    # - uses: actions/upload-artifact@v1
    #   with:
    #     name: dark-minus-theme-${{ steps.package-version.outputs.current-version}}-nightly
    #     path: dark-minus-theme-${{ steps.package-version.outputs.current-version}}.vsix
